  name: First Workflow
  on: push
  jobs:
    echo:
      runs-on: ubuntu-latest
      steps: 
        - run: echo "GitHub Action Test"
    pwd-ls:
      name: PWD & LS
      runs-on: ubuntu-latest
      steps:
        - name: Print Working Dir
          run: pwd
        - name: List Files
          run: ls -al
    checkout:
      runs-on: ubuntu-latest
      steps: 
        - uses: actions/checkout@v4.1.1
